### PR TITLE
Use scikit-learn dev wheel from artifact

### PR DESCRIPTION
**Pull request by lesteve**
I was not able to make the `pyodide build` with Pyodide dev debug working see this [build log](https://github.com/lesteve/scikit-learn-tests-pyodide/actions/runs/3928387413/jobs/6715953639)

Latest [commit](https://github.com/lesteve/scikit-learn-tests-pyodide/tree/9ec029e49a59f8a51a208694e60a8161825136d7) with my attempt.

For some reason it seems that Cython code in the neighbors returns 64 bit indices rather than 32bit ...
which causes issues like `RuntimeError: memory access out of bounds`

```python
import numpy as np
from sklearn.metrics._pairwise_distances_reduction import (
    ArgKmin,
    RadiusNeighbors,
)

rng = np.random.RandomState(0)
X = rng.randn(50).reshape(10, 5)
results = RadiusNeighbors.compute(
    X=X,
    Y=X,
    radius=3,
    metric='euclidean',
    # metric_kwargs=nn.effective_metric_params_,
    strategy="auto",
    return_distance=False,
    sort_results=True,
)
print(results[0].dtype)
print(results)
```

Probably very similar were some issues with `dbscan_inner` written in Cython that was saying expected `np_intp` got `long long` instead.

### CODE REVIEW

**Comment by rth** [comment]
> I was not able to make the pyodide build with Pyodide dev debug working see this [build log](https://github.com/lesteve/scikit-learn-tests-pyodide/actions/runs/3928387413/jobs/6715953639)

Ahh, so the issue is at runtime after import rather than at build time?

> Probably very similar were some issues with dbscan_inner written in Cython that was saying expected np_intp got long long instead.

Is there a 32 bit linux (or even windows) CI in scikit-learn currently? Sounds like 32bit arch issues.

**Comment by lesteve** [comment]
> Ahh, so the issue is at runtime after import rather than at build time?

Yes runtime.

> Is there a 32 bit linux (or even windows) CI in scikit-learn currently? Sounds like 32bit arch issues.

There is a debian 32 bit build, see [here](https://dev.azure.com/scikit-learn/scikit-learn/_build/results?buildId=51080&view=logs&jobId=8102f444-d347-5a1c-8351-04c0279c7dd4&j=aabdcdc3-bb64-5414-b357-ed024fe8659e) for a build log.

**Comment by rth** [comment]
Hmm, I tried running the test suite on alpine 32bit in docker (which is a bit closer as it uses Musl libc) and they also pass fine.

**Comment by lesteve** [comment]
I just tried to reproduce the problem I was seeing with doing `pyodide build` with a development version and I am unable to reproduce :shrug: 

Maybe this was more due to the hacks I tried to reuse a debug build `dist` and add the few things I needed in https://github.com/lesteve/scikit-learn-tests-pyodide/blob/9ec029e49a59f8a51a208694e60a8161825136d7/.github/workflows/run-tests.yml#L44-L49

Edit: the reason I wanted to do that is that because otherwise the artifact is quite big and takes a few minutes to upload and a few minutes to download.

**Pull request merged**
